env: development
isProduction: false

api:
  host: 0.0.0.0
  port: 8080
  debug: true
  swagger:
    enabled: true

logger:
  level: debug

database:
  host: mysql
  port: 3306
  username: mysql
  password: MyUs3rP@ss123
  databaseName: user-counter

redis:
  addrs:
    - redis:6379
  password: redispassword123
